# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-04 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
