# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-04 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0003_usertheta'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertheta',
            name='questions',
            field=models.ManyToManyField(blank=True, to='prep.Question'),
        ),
    ]
