# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-04 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0004_usertheta_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
